version: '2'
services:
    jhipsterapplicationune-app:
        image: jhipsterapplicationune
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterapplicationune-mysql:3306/jhipsterapplicationune?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterapplicationune-mysql:
        extends:
            file: mysql.yml
            service: jhipsterapplicationune-mysql
